gidgethub/gidgethub

gidgethub/treq.py

Encountered this while working on a tool to manage protected branches.

Strip duplicate content-length headers.

---

.travis.yml
README.rst
docs/__init__.rst
docs/abc.rst
gidgethub/__init__.py
gidgethub/abc.py
gidgethub/aiohttp.py
gidgethub/sansio.py
gidgethub/test/test_abc.py
gidgethub/test/test_aiohttp.py
gidgethub/test/test_exceptions.py
gidgethub/test/test_sansio.py
gidgethub/test/test_treq.py
gidgethub/treq.py
setup.py

Introduce the RateLimitExceeded exception and drop the automatic sleeping of requests in GitHubAPI.

Drop rate limit management

---

README.rst
gidgethub/sansio.py
gidgethub/test/test_sansio.py

If "errors" object was not provided, use the "message" field.
Fixes https://github.com/brettcannon/gidgethub/issues/49

Better handling of GitHub's 422 error.

---

gidgethub/__init__.py
setup.py

Change the version from 3.0.0.dev -> 3.0.0.dev0.
I saw this warning from `flit`.
```
Version number normalised: '3.0.0.dev' -> '3.0.0.dev0' (see PEP 440)                                  W-flit.validate
```
I haven't got it to work with flit yet, but figured this change can be made separately.

Fix development version number, per PEP 440

---

README.rst
docs/abc.rst
docs/sansio.rst
gidgethub/abc.py
gidgethub/sansio.py
gidgethub/test/test_abc.py
gidgethub/test/test_sansio.py

- Add `jwt` and `oauth_token` parameters to:
* `abc.GitHubAPI._make_request`
* `abc.GitHubAPI.get_item`
* `abc.GitHubAPI.get_iter`
* `abc.GitHubAPI.post`
* `abc.GitHubAPI.patch`
* `abc.GitHubAPI.put`
* `abc.GitHubAPI.delete`
- Add `jwt` argument to `sansio.create_headers`
- Raise `ValueError` if both `jwt` and `oauth_token` are passed in above methods
- Update the documentation
- Update the changelog
Closes https://github.com/brettcannon/gidgethub/issues/23

Allow authenticating as a GitHub App

---

.travis.yml

🍝 Reading this (https://docs.travis-ci.com/user/languages/python/#development-releases-support), trusty has outdated Python versions. Python3.7-dev in there was really Python 3.7.0a4 instead of the latest release.
With xenial, `3.7` gives us Python 3.7.1, and `3.7-dev` gives us Python 3.7.2+.

Use xenial dist in travis ci

---

gidgethub/httpx.py

The `read()` method is gone, so use the simple `content` attribute instead.
Closes #92

Fix httpx support

---

docs/changelog.rst

The changelog is in .rst. 
Dave Hirschfeld's link was in markdown.

Use ReST markup in changelog

---

docs/changelog.rst

It was using markdown link format. Changed it to restructured text.

Fix the url markup in changelog

---

docs/apps.rst

Fix missing `await` in GitHub Apps documentation

---

docs/__init__.rst
docs/sansio.rst
gidgethub/__init__.py
gidgethub/abc.py
gidgethub/httpx.py
tests/test_abc.py
tests/test_tornado.py

Closes #121 
As stated in the issue, Github enterprise server sets a response header equal to `application/json;charset=utf-8` (note: without the space separating the type and character encoding). 
The graphql method in the ABC asserts the content type header equals `application/json; charset=utf-8` (note: with space). 
The failing assertion prevents the method from successfully returning.
* Removed the content type assertion from the graphql response handling
* Replaced the response data decoding with a call to `sansio` to parse the content-type from the header and load the json based on that.
* It felt kind of dirty copying this logic out of `sansio._decode_body()` but it did have a little bit of v3 specific logic in there. Maybe a `_decode_gql_body()` is needed?
* Added a new explicit …

Fix abc.GitHubAPI.graphql() to accept response content types lacking spaces

---

docs/changelog.rst

It was missing a colon at the front of `:func:`
I've changed it to :meth:`gidgethub.abc.GitHubAPI.graphql` to be consistent with what was written in the previous changelog entry (v4.0.0)

Fix the reference to the GitHubAPI.graphql documentation in the changelog

---

docs/changelog.rst
gidgethub/apps.py
pyproject.toml
tests/test_apps.py

v 5.0.0 is not released yet, so we can bundle this in.

Specify that gidgethub requires PyJWT >= 2.0.0.

---

docs/apps.rst
docs/changelog.rst
gidgethub/apps.py

Address the issue brought up in https://github.com/brettcannon/gidgethub/discussions/155.
I removed the ``accept`` header from the API call. gidgethub puts in the default header already, so we don't have to pass in anything.

Remove the preview header from get_installation_access_token

---

docs/changelog.rst
gidgethub/sansio.py
tests/test_sansio.py

As github recommends here: https://docs.github.com/en/developers/webhooks-and-events/securing-your-webhooks#validating-payloads-from-github

Use X-Hub-Signature-256 for webhook validation

---

CONTRIBUTING.rst
docs/changelog.rst
gidgethub/sansio.py
tests/test_sansio.py

Properly handle HTTP 202 ACCEPTED as successful

---

docs/abc.rst
docs/apps.rst
docs/changelog.rst
pyproject.toml

There was a security advisory on PyJWT package: https://github.com/jpadilla/pyjwt/security/advisories/GHSA-ffqj-6fqr-9h24
I think it's best to require a minimum version of v2.4.0

Bump min PyJWT v2.4.0

---

.github/workflows/main.yml
noxfile.py
pyproject.toml

Currently the `3.9-dev` and `3.10-dev` aren't actually running any tests and being marked as a pass:
```
nox > Session tests-3.9-dev skipped: Python interpreter 3.9-dev not found.
```
https://github.com/brettcannon/gidgethub/runs/6680350315?check_suite_focus=true
```
nox > Session tests-3.10-dev skipped: Python interpreter 3.10-dev not found.
```
https://github.com/brettcannon/gidgethub/runs/6680350397?check_suite_focus=true
We can fix this by adding a variable to map from `python-version` (which may or may not end in `-dev`) to a `nox-python-version`, which does not end in `-dev`.
---
Also bump other action versions, add colour to the log output, allow testing feature branches, update Trove classifiers.

Fix 3.x-dev tests on CI

---

.github/workflows/main.yml
README.rst
docs/conf.py
gidgethub/actions.py
noxfile.py
pyproject.toml
tests/test_sansio.py

Includes PR #183 to fix CI.
3.11 needs some temporary workarounds to install dependencies, similar to Bedevere, see:
* https://github.com/python/bedevere/pull/399/files
* https://github.com/python/bedevere/pull/399#issuecomment-1073355585

Add support for Python 3.11 and drop EOL Python 3.6

---

docs/sansio.rst

Replace use of `requests` in examples with `httpx`

---

docs/conf.py

-------
This is causing linter failures on new pull requests, since Sphinx has added a
deprecation warning for the old pre-1.0 format.
This change is modeled directly on the sample documentation at https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping'
Addresses linter issues in #192 and #194

Update the intersphinx mapping to 1.0-style

---

docs/abc.rst
docs/changelog.rst
gidgethub/__init__.py
gidgethub/abc.py
tests/test_abc.py

This now supports API methods whose responses are expressed in a status
code, such as `/orgs/{org}/members/{username}` to determine if a group
contains a specific user.
-------
Per the discussion on #188 this could have been achieved through refactoring `_make_request()` to split out request construction. Looking at the intermingling of the caching logic, the rate limit counter, and the header assembly, though, it looked like any method that made use of the full set of request construction would look remarkably similar to the full `_make_request()` call. As such, I augmented the return value to include the status code instead.
Closes #188

Add a getstatus() method to gidget.abc

---

.readthedocs.yaml
docs/abc.rst
docs/changelog.rst
docs/conf.py
gidgethub/abc.py
tests/test_abc.py

This allows to do for example:
```python
async def get_stargazers_with_dates(full_repo_name):
headers = {"Accept": "application/vnd.github.v3.star+json"}
async with httpx.AsyncClient() as client:
gh = gidgethub.httpx.GitHubAPI(client, "basnijholt", oauth_token=token)
repo_owner, repo_name = full_repo_name.split("/")
stats_contributors = await gh.getitem(
f"/repos/{repo_owner}/{repo_name}/stargazers", extra_headers=headers
)
return stats_contributors
await get_stargazers_with_dates("basnijholt/adaptive-lighting")
```
Some more extra headers folks might want to use:
https://github.com/PyGithub/PyGithub/blob/300c5015d41236eb410b9cbe895258294e3500af/github/Consts.py#L58-L133
Closes #193

Add extra_headers option to get methods

---

pyproject.toml

The plan for Flit 4 is to drop support for the `[tool.flit.metadata]` project description in favour of the [`[project]` table](https://flit.pypa.io/en/stable/pyproject_toml.html#new-style-metadata), which is now standardised across different tools. 
More generally, I advise packages to always restrict the dependency to exclude the next major version of flit_core, so that I can make breaking changes. You can see the version ranges recommendations here: https://flit.pypa.io/en/stable/pyproject_toml.html#build-system-section

Set a maximum version of flit_core for build requirements

---

docs/apps.rst
docs/changelog.rst
gidgethub/apps.py
tests/test_apps.py

This PR is backwards compatible, and simply makes the expiration time of the token generated from `get_jwt` configurable.

Add expiration parameter to apps.get_jwt
