gidgethub/gidgethub

gidgethub/test/test_aiohttp.py, gidgethub/test/test_treq.py
This would have  caught the issue that #11 had to deal with.
=> Add integration tests for gidgethub.abc.getitem()

README.rst, docs/__init__.rst, docs/abc.rst, docs/aiohttp.rst, docs/sansio.rst, docs/treq.rst, gidgethub/__init__.py, gidgethub/abc.py, gidgethub/aiohttp.py, gidgethub/sansio.py, gidgethub/treq.py
Due to mypy not supporting gidgethub thanks to using a yield statement in an async function, none of the type hints were being tested.
Closes #27
=> Remove all type hints

README.rst, docs/aiohttp.rst, docs/index.rst, docs/tornado.rst, docs/treq.rst, gidgethub/test/test_tornado.py, gidgethub/tornado.py, setup.py
=> Add Tornado support

README.rst, docs/sansio.rst, gidgethub/sansio.py, gidgethub/test/test_sansio.py, setup.py
=> Add support for www-form-urlencoded

README.rst, docs/index.rst, docs/routing.rst, gidgethub/routing.py, gidgethub/test/test_routing.py
=> Introduce the routing module

.travis.yml, README.rst, gidgethub/__init__.py, gidgethub/abc.py, gidgethub/aiohttp.py, gidgethub/routing.py, gidgethub/sansio.py, gidgethub/test/test_routing.py, gidgethub/tornado.py, gidgethub/treq.py
=> Add type hints

README.rst, docs/abc.rst, docs/aiohttp.rst, docs/tornado.rst, docs/treq.rst, gidgethub/abc.py, gidgethub/aiohttp.py, gidgethub/test/test_abc.py
=> Provide a cache for GitHubAPI

README.rst, gidgethub/sansio.py, gidgethub/test/test_sansio.py, setup.py
=> Implement __str__() for RateLimit

README.rst, gidgethub/test/test_sansio.py
Didn't realize you wrote this neat library too! It's nice to read such clean async code while I'm learning.
Sorry to be that guy but I found two typos while reading through and just wanted to help out!
old | new
--- | ---
`requsting` | `requesting`
`argment` | `argument`
=> Fix two spelling mistakes

README.rst, docs/abc.rst, gidgethub/abc.py, gidgethub/test/test_abc.py
Closes https://github.com/brettcannon/gidgethub/issues/52
=> Add ``data`` keyword argument to gidgethub.abc.GitHubAPI.delete

docs/index.rst
=> Add a quickstart example

README.rst, gidgethub/__init__.py, setup.py
Fixes https://github.com/brettcannon/gidgethub/issues/59
=> Set version info to 3.0.0

docs/abc.rst
Closes https://github.com/brettcannon/gidgethub/issues/70
=> Document that you can pass `data=b""` in GitHubAPI.post

docs/changelog.rst, docs/conf.py, docs/httpx.rst, docs/index.rst, gidgethub/httpx.py, gidgethub/test/test_httpx.py, gidgethub/tornado.py, pyproject.toml
Add [`httpx`](https://www.encode.io/httpx/) backend.
=> Httpx backend

docs/changelog.rst, docs/httpx.rst, gidgethub/httpx.py, gidgethub/test/test_httpx.py
Rename AsyncClient --> Client
Fixes #90
=> Update to new httpx api

docs/__init__.rst, docs/abc.rst, docs/actions.rst, docs/changelog.rst, docs/conf.py, gidgethub/__init__.py, gidgethub/abc.py, noxfile.py, pyproject.toml, tests/samples/GraphQL/bad-credentials-401.json, tests/samples/GraphQL/curl-gql.sh, tests/samples/GraphQL/malformed-json-400.json, tests/samples/GraphQL/malformed-query-200.json, tests/samples/GraphQL/missing-variable-in-request-200.json, tests/samples/GraphQL/success-200.json, tests/test_abc.py, tests/test_exceptions.py, tests/test_sansio.py
=> Add a GraphQL API

docs/abc.rst, docs/changelog.rst, docs/sansio.rst, gidgethub/abc.py, gidgethub/sansio.py, tests/test_abc.py, tests/test_sansio.py
Closes https://github.com/brettcannon/gidgethub/issues/80
=> Allow passing in base_url to the GitHubAPI constructor

docs/sansio.rst
This was mentioned in changelog but not in this part of the doc.
Closes #
=> Add the versionchanged in sansio.format_url documentation

docs/changelog.rst, gidgethub/__init__.py, pyproject.toml
Closes https://github.com/brettcannon/gidgethub/issues/116
=> Drop cryptography dependency, and add PyJWT[crypto].

gidgethub/httpx.py
=> Fix a typing warning from mypy involving httpx

.github/workflows/main.yml, docs/changelog.rst, gidgethub/__init__.py, noxfile.py, pyproject.toml
=> Prep for 4.1.1 release

docs/abc.rst, docs/changelog.rst, docs/routing.rst, gidgethub/httpx.py, gidgethub/routing.py, pyproject.toml, tests/test_routing.py
=> Add a way to fetch the functions for a given event on a router

docs/actions.rst, docs/changelog.rst, gidgethub/actions.py, tests/test_actions.py
=> Add support for Actions environment files

docs/changelog.rst, gidgethub/__init__.py
Bumped the version to 5.0.1 and remove "in development" from the changelog.
=> Release v 5.0.1

.github/workflows/main.yml
=> Change to ``main`` branch in GH Actions file

.github/workflows/main.yml, noxfile.py
=> Test against Python 3.10 on GH Actions

docs/abc.rst, docs/changelog.rst, gidgethub/__init__.py, gidgethub/abc.py, gidgethub/sansio.py, tests/test_abc.py, tests/test_sansio.py
Needed to support the Checks API.
Updated docs and tests.
Closes https://github.com/brettcannon/gidgethub/issues/164
=> Add the iterable_key parameter to getiter.

docs/changelog.rst, gidgethub/__init__.py
=> Release v5.1.0

docs/changelog.rst, docs/conf.py, gidgethub/__init__.py
=> v5.2.0: Add changelog entry and update the version

.gitignore, docs/changelog.rst, gidgethub/__init__.py
=> Release 5.2.1

docs/apps.rst, docs/sansio.rst, tests/test_abc.py
This came up after my PR (#190)
=> Fix lint issues

docs/changelog.rst, gidgethub/abc.py
=> Make `gidgethub.abc.GitHubAPI.getiter()` iterative
